### ISSUE TITLE
line.strip()

### ISSUE THREAD

**Issue by meissnere** [ujwlkarn/Twitter-Sentiment-Analysis#2]
invalid syntax --> line.strip() -- line 58 of twitterstream.py

**Comment by SubNader** [comment]
@meissnere Which Python version are you using?

**Comment by ujjwalkarn** [comment]
@meissnere sorry for the trouble, the tutorial and the code in this repository is pretty old and is not supported anymore. I would recommend using newer tutorials available on the web in case you want to try sentiment analysis on Twitter data.
